### ISSUE TITLE
CorrelationContextAccessor should be scoped

### ISSUE THREAD

**Issue by MovGP0** [stevejgordon/CorrelationId#14] opened 2018-03-21 17:28 UTC
since `CorrelationContextAccessor` returns the correlation context of an request, it is probably a bad idea to have it as singleton, because parallel requests will overwrite the `CorrelationContext`. 

```csharp
serviceCollection.TryAddSingleton<ICorrelationContextAccessor, CorrelationContextAccessor>();
```

I guess it should be injected per-request instead: 
```csharp
serviceCollection.TryAddScoped<ICorrelationContextAccessor, CorrelationContextAccessor>();
```

**Comment by stevejgordon** [comment] 2018-03-27 11:47
Hi @MovGP0. This is by design since it needs to be (potentially) consumable from Singleton services. I have followed the patterns used by Microsoft for the HttpContextAccessor. The returned CorrelationId should be correct per scoped request despite the accessor being Singleton.

Are you seeing any issues with this when you are using it?

**Comment by stevejgordon** [comment] 2018-03-29 16:31
Marking as closed.

**Closed by stevejgordon** 2018-03-29 16:31 UTC
